#!/bin/bash
# intended to run before schema modification. it is just a data dump! the schema itself will be generated by db.py init () function.
sqlite3 data.sqlite <<!
.out file.sql 
.mode insert users
select * from users;
.mode insert release
select * from release;
.mode insert access
select * from access;
.mode insert ipn
select * from ipn;
!
